### ISSUE TITLE
Create delete function 

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Stack_Hack_1.0_server#28]
https://github.com/Ninja-Developers/Stack_Hack_1.0_server/blob/60f8625206662753e0878656d8b4e20a2af280aa/controllers/todoController.js#L83

Initially the delete function for list in  [todoController file](https://github.com/Ninja-Developers/Stack_Hack_1.0_server/blob/master/controllers/todoController.js) was left blank, because it needed to update the todo model as well, now we need this route developed for the front end. 

### What needs to be done 
When a list item is being deleted I guess all the todo items that has that list items `_id` will be deleted as well.

**Comment by imabp** [comment]
Issue solved in recent commit : )
