### ISSUE TITLE
Add comments to code

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Stack_Hack_1.0_server#29]
Add meaningful comments so to help the people who are gonna check our code in the competition.

**Comment by imabp** [comment]
@sy0837 you can try this too. And @Anoushka03  you can also do this, though not in team, but you can learn some basic git activities.

**Comment by imabp** [comment]
Anyone doing this, or shall I start this one too ?? @Souvikns  any update?

**Comment by Souvikns** [comment]
@imabp you can start. 👍

**Comment by imabp** [comment]
Commenting Done [Commit Link](https://github.com/Ninja-Developers/Stack_Hack_1.0_server/commit/8ae4f8fe93084e218abd05bc33cbcb2fb6e4560f)
