### ISSUE TITLE
Create user model

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Stack_Hack_1.0_server#30]
We need to create a user model and also change the lists and todo model accordingly, with this I think we also make some minor changes in the route, that might also have to make the changes in the front end accordingly.

**Comment by imabp** [comment]
What information of user, we should keep in our user model, name, email and password ??

**Comment by Souvikns** [comment]
I was thinking of username and password 
and not allow if a username is taken

**Comment by Souvikns** [comment]
I was thinking of keeping the authentication simple and spent more time in adding features, like creating labels and stuff.

**Comment by imabp** [comment]
Yaa we can use, bcrypt for hashing all the passwords.. and bcrypt compare.. to check the passwords and all..stuff...

**Comment by imabp** [comment]
i m thinking username, email and password. is that fine??

**Comment by Souvikns** [comment]
Then will we check for email also?

**Comment by imabp** [comment]
![image](https://user-images.githubusercontent.com/53480076/82833542-e1b54080-9edb-11ea-9bd5-0731c0d5d478.png)

**Comment by Souvikns** [comment]
Yeah I get it but will be sending email and check if the user is legit? or just keep it.

**Comment by imabp** [comment]
just keeping it for now, later on, we can add features..like.. sending emails about to do and all... stuff..

**Comment by Souvikns** [comment]
ok! So shall I assign this to you?

**Comment by imabp** [comment]
I am not sure bout the routing stuff.. but I can create the user model and hashing of password before saving it..to database

**Comment by Souvikns** [comment]
Let's create other issues that have this issue as a dependency and divide the work.

**Comment by imabp** [comment]
yaa fine bro.
